### ISSUE TITLE
Colors not showing correctly

### ISSUE THREAD

**Issue by Anna-28** [FliPPeh/rendermap#5]
Map images don't show colors correctly, except when on the edge of the colored area.

Ingame view of what the map should look like:
![2017-01-28_10 09 05](https://cloud.githubusercontent.com/assets/9390699/22578737/dde9ec9e-ea2f-11e6-8203-540044bae85d.png)

Website/image view of the map:
![sillyflowermap](https://cloud.githubusercontent.com/assets/9390699/22578739/e3f4c2b2-ea2f-11e6-87a3-944b0eedda7b.PNG)

![sillyflowermap2](https://cloud.githubusercontent.com/assets/9390699/22578741/e6d56b26-ea2f-11e6-86aa-7630b6be06a0.png)

**Comment by Anna-28** [comment]
Oddly it seems that the colored outlines that do show up change color each time the map image is generated:

![sillyflowermap3](https://cloud.githubusercontent.com/assets/9390699/22621590/19c17978-eb8c-11e6-9590-69c218e40c38.png)

![sillyflowermap4](https://cloud.githubusercontent.com/assets/9390699/22621591/288c115c-eb8c-11e6-86f7-fa41bb09e017.png)

![sillyflowermap5](https://cloud.githubusercontent.com/assets/9390699/22621593/2b375a24-eb8c-11e6-863a-950cb508f8ed.png)

![sillyflowermap6](https://cloud.githubusercontent.com/assets/9390699/22621594/2d299f5e-eb8c-11e6-9f2b-0dfe11604ebd.png)

**Comment by Anna-28** [comment]
Link to website which contains the map image: http://minecraftonline.com/cgi-bin/controlpanel?maps=3044

**Comment by FliPPeh** [comment]
Fixed in 90e4c4dd442328e277d151973628a36705a4be48
